### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by esurov**
Replaced the default readme with project-specific info

### CODE REVIEW

**Comment by SKSritharan** [comment]
Hi @esurov, Thank you for submitting your pull request to update the README file! I really appreciate your effort to enhance our documentation, it’s essential for helping new users get started with the project.
While documentation updates are valuable, I’d love to see you contribute more functional features or improvements to the system. These kinds of contributions have a significant impact on the project’s growth and usability. ❤️

**Comment by esurov** [comment]
Hi @SKSritharan , Thank you for your prompt response.
I totally have in mind more profound PRs. It was just the first obstacle on the way: the lack of the documentation.
So I wanted to address it first.
More PRs are to follow.
Wish you a nice weekend!
And thanks again for the feedback.
Kind regards,
-Gene

**Comment by esurov** [comment]
BTW, @SKSritharan , 
If you have any ideas for the apps improvement please feel free to open an issue with `help-wanted` tag.

**Comment by SKSritharan** [comment]
Hi @esurov,
I'm genuinely excited to hear that you're planning more significant contributions. I'll keep an eye out for your future PRs! As for improvements, I’ll definitely consider adding some issues with the help-wanted tag,
Enjoy your weekend as well, and thanks again for your dedication!

**Pull request merged**
